language: android
android:
        components:
                - platform-tools
                - build-tools-27.0.2
                - android-26
                - extra-android-m2repository
script:
        - ./gradlew assembleDebug
before_install:
        - chmod +x gradlew
