language: android
android:
  components:
  - platform-tools
  - build-tools-28.0.3
  - android-28
  - extra-android-m2repository
before_install:
- chmod +x gradlew
install:
- echo y | sdkmanager "ndk-bundle"
- echo y | sdkmanager "cmake;3.10.2.4988404"
- echo y | sdkmanager "lldb;3.1"
#  - sdkmanager --update
before_script:
- export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle
script:
  - ./gradlew assembleProdDebug
